---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app # Name of your application
  namespace: argocd # Namespace where Argo CD is installed
spec:
  project: default # Project in Argo CD
  destination:
    server: 'https://kubernetes.default.svc' # Kubernetes cluster URL
    namespace: my-app-namespace # Target namespace for deployment
  source:
    repoURL: 'https://github.com/your-org/your-repo.git' # Your application repository
    targetRevision: HEAD # Branch or tag to deploy

